### PR TITLE
RFC: Add corodova-paramedic

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Do not merge!!!

I thought I could try to add cordova paramedic for testing and CI to this project.

What do you think of it.

For now the PR only starts the implementation.

**TODO**

- [ ] Finish porting tests to jasmine
- [ ] Add saucelabs
- [ ] Add travis
- [ ] Make eslint work in test file
- [ ] Add build badge to README
- [ ] .....

### CODE REVIEW

**Comment by j3k0** [comment]
Nice. I'll take a look this week

**Comment by j3k0** [comment]
Seems like a good start. First time I hear of `cordova-paramedic`, interesting.

If I understand correctly, so far the test confirm that the plugin installs correctly and exports the expected functions. Paramedic installs the plugin on simulators?

**Comment by NiklasMerz** [comment]
Yes paramedic installs the plugin with a test app on simulators and runs the jasmine tests automatically. You can also define manual tests. It also works automated with Saucelabs and Travis.

This plugins uses paramedic for some automated tests: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio. Have look [here](https://travis-ci.org/NiklasMerz/cordova-plugin-fingerprint-aio/jobs/437253658) for some results. The Apache Cordova team also uses paramedic for CI with some plugins. I think it is good to know if the plugin compiles and some functions don´t get broken.

The PR right now is very small. All of your tests should be ported to jasmine and setting up Travis with Saucelabs needs to be done.

**Comment by j3k0** [comment]
Hey @NiklasMerz, plans on finishing this? Would be nice. In case not, we can close this.

**Comment by NiklasMerz** [comment]
I could try to finish this is the next couple days when I find time. I think you should create a Saucelabs account and add it to you Travis account when it is ready. Did you try the tests locally?

**Comment by NiklasMerz** [comment]
This needs to much work done and as far as I know real testing for the share extension is not possible so I am closing this.

**Pull request closed without merging**
